version: '3.7'
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    restart: always
    
  api:
    container_name: backend
    restart: always
    build: .
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/usr/src/auth
      - ./node_modules:/usr/src/auth/node_modules
    ports:
      - '5000:5000'
    command: npm start
