version: '3.7'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
      POSTGRES_DB: ${TYPEORM_DATABASE}
    ports:
      - '5432:5432'
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    restart: always
    
  api:
    container_name: api
    restart: always
    build: .
    env_file:
      - .env
    volumes:
      - ./:/usr/src/auth
      - ./node_modules:/usr/src/auth/node_modules
    ports:
      - '5000:5000'
    command: npm start

